#include "showcase.hpp"

#include "button.hpp"
#include "flex_panel.hpp"
#include "gauge_dial.hpp"
#include "hero_chart.hpp"
#include "knob.hpp"
#include "label.hpp"
#include "list_box.hpp"
#include "logging.hpp"
#include "panel.hpp"
#include "progress_bar.hpp"
#include "shadow_card.hpp"
#include "slider.hpp"
#include "theme.hpp"
#include "toggle_switch.hpp"
#include "trend_line.hpp"
#include "ui_file.hpp"

#include <chrono>
#include <cstdio>

#include "showcase_ui.gen.hpp"  // packed by ui_embed at build time
#include "showcase_assets.gen.hpp"  // generated by asset_gen at build time

namespace zb::app::showcase
{
    namespace
    {
        // the design-file grammar carries no alignment attribute yet
        // (backlog): center each materialized caption vertically; buttons
        // additionally center horizontally (wire_controls). Descends
        // through flex containers — the is_flex_container() guard is the
        // ui_builder pattern (only FlexPanel overrides it, so the cast is
        // safe without RTTI)
        void center_text(zb::ui::Widget &w)
        {
            w.set_v_align(zb::ui::Widget::v_align::center);
            if (w.is_flex_container())
            {
                for (const auto &item :
                     static_cast<zb::ui::FlexPanel &>(w).get_items())
                {
                    center_text(*item.child);
                }
            }
        }

        zb::input::input_event mouse_ev(const zb::input::input_type type,
                                        const int x, const int y)
        {
            zb::input::input_event ev{};
            ev.type = type;
            ev.x = x;
            ev.y = y;
            ev.touch_id = 0;
            return ev;
        }

// FNV-1a over the framebuffer bytes: two renders of the same widget
// state must hash identically (the PIXELS MATCH self-check). Hashed as
// raw bytes -- the per-pixel Color is 4 bytes at 32bpp and 2 at 16bpp,
// so a word-wise read would stride past the buffer on embedded builds
uint32_t fnv1a(const uint8_t *data, const std::size_t n)
        {
            uint32_t h = 2166136261u;
            for (std::size_t i = 0; i < n; ++i)
            {
                h ^= data[i];
                h *= 16777619u;
            }
            return h;
        }
    }

    void Showcase::create_window(uint32_t max_client_width,
                                 uint32_t max_client_height)
    {
        make_window(max_client_width, max_client_height, nullptr);
    }

    void Showcase::create_window(uint32_t max_client_width,
                                 uint32_t max_client_height, void *buffer)
    {
        make_window(max_client_width, max_client_height, buffer);
    }

    void Showcase::make_window(uint32_t max_client_width,
                               uint32_t max_client_height, void *buffer)
    {
        _width = static_cast<int32_t>(max_client_width);
        _height = static_cast<int32_t>(max_client_height);
        window_ = zb::make_shared<CanvasWindow>();
        window_->create(max_client_width, max_client_height, buffer);
        window_->set_title("Imprint UI -- showcase");
        // design-file host: layout is driven by the window (batch J5)
        window_->set_auto_layout(true);
        // V-2: the showcase ships dark (the README face); the theme
        // button offers the switch back. The generation bump makes the
        // first frame present the whole buffer
        dark_ = true;
        zb::ui::set_theme(zb::ui::dark_theme());
        sub_painted_ = window_->painted.subscribe([this](const void *) {
            if (bench_active_ && window_)
            {
                ++bench_paints_;
                int x = 0, y = 0, w = 0, h = 0;
                window_->dirty_region(x, y, w, h);
                bench_px_ += static_cast<long long>(w) * h;
            }
        });
        load_pages();
        install_chart();
        install_assets();
        install_dashboard();
        wire_controls();
        show_page(0);
        // F-2 glue: the chart reveal runs on its own once a host pumps
        // frames (wasm rAF, the NDS vblank poll, the shell-less
        // recorder); event-driven shells advance it on input events
        replay();
    }

    void Showcase::load_pages()
    {
        static const char *const names[3] =
            {"hero.ui", "gallery.ui", "dashboard.ui"};
        for (int i = 0; i < 3; ++i)
        {
            const embedded_ui_file *doc = find_ui_file(names[i]);
            if (doc == nullptr)
            {
                LW << "showcase: embedded document '" << names[i] << "' missing";
                continue;
            }
            bool ok = false;
            zb::ui::ui_node tree = zb::ui::parse_ui_text(
                reinterpret_cast<const char *>(doc->data), &ok);
            if (!ok)
            {
                LW << "showcase: '" << names[i] << "' yields no widget; skipped";
                continue;
            }
            auto page = std::make_unique<zb::ui::FlexPanel>();
            page->set_size(_width, _height);
            zb::ui::build(*page, tree);
            center_text(*page);
            pages_[i] = std::move(page);
        }
    }

    // V-2: mount the hero chart into its design-file slot. The slot is a
    // plain panel with no declared size (the L-3 trap sets undeclared
    // widths to zero), so the app sizes it here -- the frame width is
    // shell-owned knowledge the .ui file must not guess
    void Showcase::install_chart()
    {
        if (pages_[0] == nullptr)
        {
            return;
        }
        auto *slot = pages_[0]->find_by_id("chart_slot");
        if (slot == nullptr)
        {
            LW << "showcase: chart_slot missing from hero.ui";
            return;
        }
        // keep the 256x192 embedded fit: the compact rows free the
        // vertical budget, the chart takes what the frame can spare
        const int chart_h = _height >= 240 ? 56 : 40;
        slot->set_size(_width - 16, chart_h);
        auto chart = std::make_unique<HeroChart>();
        chart->set_size(_width - 16, chart_h);
        chart_ = chart.get();
        static_cast<zb::ui::Panel *>(slot)->add_child(std::move(chart));
    }

    // V-2: materialize the procedural assets once into the build's pixel
    // layout, then hand views to the gallery widgets -- the ball as an
    // alpha-blitted image, the shadow through the 9-slice card. Both
    // buffers are owned here so the views outlive every widget
    void Showcase::install_assets()
    {
        if (pages_[1] == nullptr)
        {
            return;
        }
        const auto &ball_src = showcase_assets::logo_ball_view;
        const auto &shadow_src = showcase_assets::card_shadow_view;
        const std::size_t ball_n =
            static_cast<std::size_t>(ball_src.width) * ball_src.height;
        const std::size_t shadow_n =
            static_cast<std::size_t>(shadow_src.width) * shadow_src.height;
        // one resize before any view is taken: growth would invalidate
        asset_pixels_.resize(ball_n + shadow_n);
        for (std::size_t i = 0; i < ball_n; ++i)
        {
            asset_pixels_[i] = rgba_color(ball_src.rgba + 4 * i);
        }
        for (std::size_t i = 0; i < shadow_n; ++i)
        {
            asset_pixels_[ball_n + i] = rgba_color(shadow_src.rgba + 4 * i);
        }
        ball_img_ = {asset_pixels_.data(),
                     static_cast<int>(ball_src.width),
                     static_cast<int>(ball_src.height),
                     static_cast<int>(ball_src.width)};
        shadow_img_ = {asset_pixels_.data() + ball_n,
                       static_cast<int>(shadow_src.width),
                       static_cast<int>(shadow_src.height),
                       static_cast<int>(shadow_src.width)};

        if (auto *logo_slot = pages_[1]->find_by_id("logo_slot"))
        {
            static_cast<zb::ui::Panel *>(logo_slot)
                ->add_child(std::make_unique<AlphaImage>(ball_img_));
        }
        if (auto *shadow_slot = pages_[1]->find_by_id("shadow_slot"))
        {
            auto card = std::make_unique<ShadowCard>(shadow_img_, ball_img_);
            card->set_size(shadow_slot->get_size());
            static_cast<zb::ui::Panel *>(shadow_slot)->add_child(std::move(card));
        }
    }

    void Showcase::install_dashboard()
    {
        // V-5 step 3: wire the factory-console page. The design file
        // declares the static structure; this seeds the trend, syncs the
        // setpoint knob/slider pair, feeds the alarm list from the plant
        // switches, and hooks the self-check button.
        if (pages_[2] == nullptr)
        {
            return;
        }
        auto *page = pages_[2].get();
        temp_gauge_ = static_cast<zb::ui::GaugeDial *>(page->find_by_id("temp_gauge"));
        press_gauge_ = static_cast<zb::ui::GaugeDial *>(page->find_by_id("press_gauge"));
        flow_gauge_ = static_cast<zb::ui::GaugeDial *>(page->find_by_id("flow_gauge"));
        trend_ = static_cast<zb::ui::TrendLine *>(page->find_by_id("trend"));
        setpoint_knob_ = static_cast<zb::ui::Knob *>(page->find_by_id("setpoint_knob"));
        setpoint_slider_ = static_cast<zb::ui::Slider *>(page->find_by_id("setpoint_slider"));
        knob_readout_ = static_cast<zb::ui::Label *>(page->find_by_id("knob_readout"));
        console_ppm_ = static_cast<zb::ui::Label *>(page->find_by_id("console_ppm"));
        pump_toggle_ = static_cast<zb::ui::ToggleSwitch *>(page->find_by_id("pump_toggle"));
        coolant_toggle_ = static_cast<zb::ui::ToggleSwitch *>(page->find_by_id("coolant_toggle"));
        alarm_list_ = static_cast<zb::ui::ListBox *>(page->find_by_id("alarm_list"));
        bench_btn_ = static_cast<zb::ui::Button *>(page->find_by_id("bench_btn"));
        bench_out_ = static_cast<zb::ui::Label *>(page->find_by_id("bench_out"));
        bench_in_ = static_cast<zb::ui::Label *>(page->find_by_id("bench_in"));

        if (trend_ != nullptr)
        {
            static const int kSeed[8] = {10, 22, 16, 30, 24, 38, 32, 44};
            trend_->set_series(kSeed, 8);
        }

        const auto set_readout = [this](const int v) {
            char buf[16];
            std::snprintf(buf, sizeof buf, "%d", v);
            if (knob_readout_ != nullptr)
            {
                knob_readout_->set_text(buf);
            }
        };
        if (setpoint_knob_ != nullptr && setpoint_slider_ != nullptr)
        {
            // the design file carries one setpoint; push it to the other
            // end of the pair at mount (programmatic setters are silent)
            setpoint_slider_->set_value(setpoint_knob_->get_value());
            sub_setpoint_knob_ = setpoint_knob_->changed.subscribe([this, set_readout](const int v) {
                setpoint_slider_->set_value(v);
                set_readout(v);
            });
            sub_setpoint_slider_ = setpoint_slider_->changed.subscribe([this, set_readout](const int v) {
                setpoint_knob_->set_value(v);
                set_readout(v);
            });
        }

        const auto post_alarm = [this](const char *msg) {
            alarm_log_.push_back(msg);
            while (alarm_log_.size() > 3)
            {
                alarm_log_.erase(alarm_log_.begin());
            }
            if (alarm_list_ != nullptr)
            {
                alarm_list_->set_items(alarm_log_);
            }
        };
        if (pump_toggle_ != nullptr)
        {
            sub_pump_ = pump_toggle_->changed.subscribe(
                [post_alarm](const bool on) { post_alarm(on ? "PUMP ON" : "PUMP OFF"); });
        }
        if (coolant_toggle_ != nullptr)
        {
            sub_coolant_ = coolant_toggle_->changed.subscribe(
                [post_alarm](const bool on) { post_alarm(on ? "COOLANT ON" : "COOLANT OFF"); });
        }

        if (auto *dash_back_btn = static_cast<zb::ui::Button *>(page->find_by_id("dash_back_btn"));
            dash_back_btn != nullptr)
        {
            sub_dash_back_ = dash_back_btn->clicked.subscribe([this] { show_page(0); });
        }
        if (bench_btn_ != nullptr)
        {
            sub_bench_ = bench_btn_->clicked.subscribe([this] { run_bench(); });
        }
    }

    void Showcase::wire_controls()
    {
        if (pages_[0] != nullptr)
        {
            auto *start_btn = static_cast<zb::ui::Button *>(pages_[0]->find_by_id("start_btn"));
            auto *stop_btn = static_cast<zb::ui::Button *>(pages_[0]->find_by_id("stop_btn"));
            auto *gallery_btn = static_cast<zb::ui::Button *>(pages_[0]->find_by_id("gallery_btn"));
            theme_btn_ = static_cast<zb::ui::Button *>(pages_[0]->find_by_id("theme_btn"));
            state_label_ = static_cast<zb::ui::Label *>(pages_[0]->find_by_id("state_value"));
            cpu_bar_ = static_cast<zb::ui::ProgressBar *>(pages_[0]->find_by_id("cpu_bar"));
            mem_bar_ = static_cast<zb::ui::ProgressBar *>(pages_[0]->find_by_id("mem_bar"));
            temp_bar_ = static_cast<zb::ui::ProgressBar *>(pages_[0]->find_by_id("temp_bar"));
            auto *replay_btn = static_cast<zb::ui::Button *>(pages_[0]->find_by_id("replay_btn"));
            if (start_btn != nullptr)
            {
                sub_start_ = start_btn->clicked.subscribe([this] { start(); });
            }
            if (stop_btn != nullptr)
            {
                sub_stop_ = stop_btn->clicked.subscribe([this] { stop(); });
            }
            if (replay_btn != nullptr)
            {
                sub_replay_ = replay_btn->clicked.subscribe([this] { replay(); });
            }
            if (gallery_btn != nullptr)
            {
                sub_gallery_ = gallery_btn->clicked.subscribe([this] { show_page(1); });
            }
            auto *dash_btn = static_cast<zb::ui::Button *>(pages_[0]->find_by_id("dash_btn"));
            if (dash_btn != nullptr)
            {
                sub_dashboard_ = dash_btn->clicked.subscribe([this] { show_page(2); });
            }
            if (theme_btn_ != nullptr)
            {
                sub_theme_ = theme_btn_->clicked.subscribe([this] { toggle_theme(); });
                // the design file ships the light-theme caption; the
                // showcase boots dark, so the button offers light first
                theme_btn_->set_text(dark_ ? "LIGHT" : "DARK");
            }
        }
        if (pages_[1] != nullptr)
        {
            auto *back_btn = static_cast<zb::ui::Button *>(pages_[1]->find_by_id("back_btn"));
            demo_slider_ = static_cast<zb::ui::Slider *>(pages_[1]->find_by_id("demo_slider"));
            demo_bar_ = static_cast<zb::ui::ProgressBar *>(pages_[1]->find_by_id("demo_bar"));
            if (back_btn != nullptr)
            {
                sub_back_ = back_btn->clicked.subscribe([this] { show_page(0); });
            }
            if (demo_slider_ != nullptr && demo_bar_ != nullptr)
            {
                sub_slider_ = demo_slider_->changed.subscribe(
                    [this](const int v) { demo_bar_->set_value(v); });
            }
        }

        // button captions also center horizontally (every widget is
        // vertically centered at materialization)
        const auto center_button = [this](const char *id) {
            for (auto &page : pages_)
            {
                if (page != nullptr)
                {
                    if (auto *w = page->find_by_id(id))
                    {
                        w->set_h_align(zb::ui::Widget::h_align::center);
                    }
                }
            }
        };
        for (const char *id : {"start_btn", "stop_btn", "gallery_btn", "theme_btn",
                               "replay_btn", "dash_btn", "back_btn", "demo_button",
                               "dash_back_btn", "bench_btn"})
        {
            center_button(id);
        }
    }

    void Showcase::show_page(const int index)
    {
        if (index < 0 || index > 2 || pages_[index] == nullptr)
        {
            return;
        }
        zb::ui::Panel &root = window_->root();
        if (mounted_ != nullptr)
        {
            // park the outgoing page back into the array (the tree owns
            // it while mounted, so pages_[current_] was empty). The
            // tree-mutation protocol (batch J3): remove_from evicts the
            // subtree from the input dispatcher first -- the gallery
            // button being pressed lives on the outgoing page, and a
            // raw Panel::remove_child would leave the dispatcher's
            // pressed_target/focus pointing into the parked subtree
            if (auto parked = window_->remove_from(root, mounted_))
            {
                pages_[current_].reset(
                    static_cast<zb::ui::FlexPanel *>(parked.release()));
            }
            mounted_ = nullptr;
        }
        // the plant runs while the console is on screen (event-driven:
        // each input event advances the sim by one deterministic sample)
        if (index == 2)
        {
            running_ = true;
        }
        zb::ui::FlexPanel *raw = pages_[index].get();
        root.add_child(std::move(pages_[index]));
        mounted_ = raw;
        current_ = index;
        root.layout();
    }

    void Showcase::set_state(const char *text)
    {
        if (state_label_ != nullptr)
        {
            state_label_->set_text(text);
        }
    }

    void Showcase::start()
    {
        if (cpu_bar_ != nullptr && cpu_bar_->get_value() >= cpu_bar_->get_max())
        {
            // DONE: restart from zero
            cpu_bar_->set_value(0);
            if (mem_bar_ != nullptr) mem_bar_->set_value(0);
            if (temp_bar_ != nullptr) temp_bar_->set_value(0);
        }
        running_ = true;
        set_state("RUNNING");
    }

    void Showcase::stop()
    {
        running_ = false;
        set_state("IDLE");
    }

    void Showcase::toggle_theme()
    {
        dark_ = !dark_;
        zb::ui::set_theme(dark_ ? zb::ui::dark_theme() : zb::ui::light_theme());
        if (theme_btn_ != nullptr)
        {
            theme_btn_->set_text(dark_ ? "LIGHT" : "DARK");
        }
    }

    // F-2 preview glue: restart the chart reveal. One Tween step per
    // paint() request (frame index = paint call), deterministic for the
    // recorder and the automation suites; hosts that pump frames see the
    // full animation, event-driven shells advance it on input
    void Showcase::replay()
    {
        reveal_.start(0, 255, 8);
        if (chart_ != nullptr)
        {
            chart_->set_progress(0);
        }
    }

    // one deterministic step per input event while running (repaint on
    // demand: there is no animation loop); the status label changes only
    // on the discrete DONE transition, never in this per-event path
    void Showcase::advance()
    {
        if (cpu_bar_ != nullptr) cpu_bar_->set_value(cpu_bar_->get_value() + 1);
        if (mem_bar_ != nullptr) mem_bar_->set_value(mem_bar_->get_value() + 2);
        if (temp_bar_ != nullptr) temp_bar_->set_value(temp_bar_->get_value() + 3);
        if (cpu_bar_ != nullptr && mem_bar_ != nullptr && temp_bar_ != nullptr &&
            cpu_bar_->get_value() >= cpu_bar_->get_max() &&
            mem_bar_->get_value() >= mem_bar_->get_max() &&
            temp_bar_->get_value() >= temp_bar_->get_max())
        {
            running_ = false;
            set_state("DONE");
        }
    }

    zb::SharedPtr<IWindow> Showcase::window() noexcept
    {
        return window_;
    }

    void Showcase::input(const zb::input::input_event &ev) noexcept
    {
        if (!bench_active_ && running_)
        {
            if (current_ == 2)
            {
                advance_dashboard();
            }
            else
            {
                advance();
            }
        }
        update_input_echo(ev);
        window_->input(ev);
    }

    // V-5 step 3: one deterministic plant sample per input event while
    // the console is mounted (the self-check freezes the sim: its own
    // synthetic drags must not move the trend between the pixel captures)
    void Showcase::advance_dashboard()
    {
        ++sample_;
        const int wave = sample_ * 7 % 40;
        if (trend_ != nullptr)
        {
            trend_->append(20 + wave);
        }
        if (temp_gauge_ != nullptr)
        {
            temp_gauge_->set_value(100 + sample_ * 3 % 40);
        }
        if (press_gauge_ != nullptr)
        {
            press_gauge_->set_value(40 + sample_ * 5 % 30);
        }
        if (flow_gauge_ != nullptr)
        {
            flow_gauge_->set_value(25 + wave);
        }
        if (console_ppm_ != nullptr)
        {
            char buf[16];
            std::snprintf(buf, sizeof buf, "%04d u/min", sample_ * 12 % 10000);
            console_ppm_->set_text(buf);
        }
    }

    // the input echo: the last decoded event, lifted live on the console
    void Showcase::update_input_echo(const zb::input::input_event &ev)
    {
        if (bench_in_ == nullptr)
        {
            return;
        }
        using t = zb::input::input_type;
        const char *kind = "EV";
        switch (ev.type)
        {
        case t::mouse_left_down:
            kind = "TL DOWN";
            break;
        case t::mouse_left_up:
            kind = "TL UP";
            break;
        case t::mouse_move:
            kind = "MOVE";
            break;
        case t::mouse_wheel:
            kind = "WHEEL";
            break;
        case t::key_down:
            kind = "KEY";
            break;
        case t::key_up:
            kind = "KEY+";
            break;
        default:
            kind = "EV";
            break;
        }
        char buf[48];
        std::snprintf(buf, sizeof buf, "%s %d,%d", kind, ev.x, ev.y);
        bench_in_->set_text(buf);
    }

    // SELF-CHECK: drive the setpoint knob with real drag events (the
    // exact input path a touch panel takes) and prove that two renders
    // of the same state hash the framebuffer byte-identically -- the
    // input-driven "PIXELS MATCH" stamp the README points at. Each
    // round lifts the value by a fixed drag then returns it; the up and
    // the returned states must each be pixel-stable across rounds.
    void Showcase::run_bench()
    {
        if (setpoint_knob_ == nullptr || bench_active_)
        {
            return;
        }
        bench_active_ = true;
        bench_matched_ = true;
        bench_paints_ = 0;
        bench_px_ = 0;
        bench_hash_[0] = 0;
        bench_hash_[1] = 0;
        bench_t0_ = std::chrono::steady_clock::now();

        const auto p = setpoint_knob_->get_absolute_position();
        const auto s = setpoint_knob_->get_size();
        const int cx = p.x + s.width / 2;
        const int cy = p.y + s.height / 2;
        const int dy = 2;  // 2 px: one widget height spans the whole range

        const int rounds = 3;
        for (int r = 0; r < rounds; ++r)
        {
            this->input(mouse_ev(zb::input::input_type::mouse_left_down, cx, cy));
            this->input(mouse_ev(zb::input::input_type::mouse_move, cx, cy - dy));
            this->input(mouse_ev(zb::input::input_type::mouse_left_up, cx, cy - dy));
            bench_check_hash(0);
            this->input(mouse_ev(zb::input::input_type::mouse_left_down, cx, cy));
            this->input(mouse_ev(zb::input::input_type::mouse_move, cx, cy + dy));
            this->input(mouse_ev(zb::input::input_type::mouse_left_up, cx, cy + dy));
            bench_check_hash(1);
        }

        bench_active_ = false;
        const double secs =
            std::chrono::duration<double>(std::chrono::steady_clock::now() - bench_t0_)
                .count();
        // sub-10ms runs (headless tests, the NDS poll) read "--fps";
        // the wall-clock frame rate is only meaningful against a real
        // pump rate
        const int fps = secs >= 0.010 ? static_cast<int>(bench_paints_ / secs) : -1;
        char buf[96];
        const long long px_per_frame =
            bench_paints_ > 0 ? bench_px_ / bench_paints_ : 0;
        if (fps < 0)
        {
            std::snprintf(buf, sizeof buf, "FPS:--");
        }
        else
        {
            std::snprintf(buf, sizeof buf, "FPS:%d", fps);
        }
        std::string out = std::string("RT:") + std::to_string(rounds) +
                          " PX/F:" + std::to_string(px_per_frame) + " " + buf;
        if (bench_out_ != nullptr)
        {
            bench_out_->set_text((out + (bench_matched_ ? "  MATCH" : "  MISMATCH")).c_str());
        }
    }

    void Showcase::bench_check_hash(const int half)
    {
        const uint32_t h = buffer_hash();
        if (bench_hash_[half] == 0)
        {
            bench_hash_[half] = h;
        }
        else if (bench_hash_[half] != h)
        {
            bench_matched_ = false;
        }
    }

    uint32_t Showcase::buffer_hash() const
    {
        const auto *data = static_cast<const uint8_t *>(window_->data());
        if (data == nullptr)
        {
            return 0;
        }
        const std::size_t pixels = static_cast<std::size_t>(window_->width()) *
                                   static_cast<std::size_t>(window_->height());
        return fnv1a(data, pixels * sizeof(zb::ui::core::Color));
    }

    void Showcase::paint() noexcept
    {
        // one deterministic tween step per paint request, BEFORE the
        // frame renders; marking the chart dirty keeps is_dirty() true
        // while a frame is owed, so idle-polling shells (NDS, linux-fb)
        // keep pumping and stop the moment the reveal lands
        if (reveal_.active())
        {
            reveal_.step();
            if (chart_ != nullptr)
            {
                chart_->set_progress(reveal_.value());
            }
        }
        window_->paint();
    }

    bool Showcase::is_dirty() const noexcept
    {
        return window_ && window_->is_dirty();
    }

    bool Showcase::dirty_region(int &x, int &y, int &rw, int &rh) const noexcept
    {
        return window_ && window_->dirty_region(x, y, rw, rh);
    }

    void Showcase::on_painting(const event::PAINT_EVENT::EventHandler handler) noexcept
    {
        if (window_) window_->painting += handler;
    }

    void Showcase::on_painted(const event::PAINT_EVENT::EventHandler handler) noexcept
    {
        if (window_) window_->painted += handler;
    }

    void Showcase::on_closing(const event::CLOSE_EVENT::EventHandler handler) noexcept
    {
        if (window_) window_->closing += handler;
    }

    void Showcase::on_closed(const event::CLOSE_EVENT::EventHandler handler) noexcept
    {
        if (window_) window_->closed += handler;
    }
}  // namespace zb::app::showcase
