#include "showcase.hpp"

#include "button.hpp"
#include "flex_panel.hpp"
#include "hero_chart.hpp"
#include "label.hpp"
#include "logging.hpp"
#include "panel.hpp"
#include "progress_bar.hpp"
#include "shadow_card.hpp"
#include "slider.hpp"
#include "theme.hpp"
#include "ui_file.hpp"

#include "showcase_ui.gen.hpp"  // packed by ui_embed at build time
#include "showcase_assets.gen.hpp"  // generated by asset_gen at build time

namespace zb::app::showcase
{
    namespace
    {
        // the design-file grammar carries no alignment attribute yet
        // (backlog): center each materialized caption vertically; buttons
        // additionally center horizontally (wire_controls). Descends
        // through flex containers — the is_flex_container() guard is the
        // ui_builder pattern (only FlexPanel overrides it, so the cast is
        // safe without RTTI)
        void center_text(zb::ui::Widget &w)
        {
            w.set_v_align(zb::ui::Widget::v_align::center);
            if (w.is_flex_container())
            {
                for (const auto &item :
                     static_cast<zb::ui::FlexPanel &>(w).get_items())
                {
                    center_text(*item.child);
                }
            }
        }
    }

    void Showcase::create_window(uint32_t max_client_width,
                                 uint32_t max_client_height)
    {
        make_window(max_client_width, max_client_height, nullptr);
    }

    void Showcase::create_window(uint32_t max_client_width,
                                 uint32_t max_client_height, void *buffer)
    {
        make_window(max_client_width, max_client_height, buffer);
    }

    void Showcase::make_window(uint32_t max_client_width,
                               uint32_t max_client_height, void *buffer)
    {
        _width = static_cast<int32_t>(max_client_width);
        _height = static_cast<int32_t>(max_client_height);
        window_ = zb::make_shared<CanvasWindow>();
        window_->create(max_client_width, max_client_height, buffer);
        window_->set_title("Imprint UI -- showcase");
        // design-file host: layout is driven by the window (batch J5)
        window_->set_auto_layout(true);
        // V-2: the showcase ships dark (the README face); the theme
        // button offers the switch back. The generation bump makes the
        // first frame present the whole buffer
        dark_ = true;
        zb::ui::set_theme(zb::ui::dark_theme());
        load_pages();
        install_chart();
        install_assets();
        wire_controls();
        show_page(0);
        // F-2 glue: the chart reveal runs on its own once a host pumps
        // frames (wasm rAF, the NDS vblank poll, the shell-less
        // recorder); event-driven shells advance it on input events
        replay();
    }

    void Showcase::load_pages()
    {
        static const char *const names[2] = {"hero.ui", "gallery.ui"};
        for (int i = 0; i < 2; ++i)
        {
            const embedded_ui_file *doc = find_ui_file(names[i]);
            if (doc == nullptr)
            {
                LW << "showcase: embedded document '" << names[i] << "' missing";
                continue;
            }
            bool ok = false;
            zb::ui::ui_node tree = zb::ui::parse_ui_text(
                reinterpret_cast<const char *>(doc->data), &ok);
            if (!ok)
            {
                LW << "showcase: '" << names[i] << "' yields no widget; skipped";
                continue;
            }
            auto page = std::make_unique<zb::ui::FlexPanel>();
            page->set_size(_width, _height);
            zb::ui::build(*page, tree);
            center_text(*page);
            pages_[i] = std::move(page);
        }
    }

    // V-2: mount the hero chart into its design-file slot. The slot is a
    // plain panel with no declared size (the L-3 trap sets undeclared
    // widths to zero), so the app sizes it here -- the frame width is
    // shell-owned knowledge the .ui file must not guess
    void Showcase::install_chart()
    {
        if (pages_[0] == nullptr)
        {
            return;
        }
        auto *slot = pages_[0]->find_by_id("chart_slot");
        if (slot == nullptr)
        {
            LW << "showcase: chart_slot missing from hero.ui";
            return;
        }
        // keep the 256x192 embedded fit: the compact rows free the
        // vertical budget, the chart takes what the frame can spare
        const int chart_h = _height >= 240 ? 56 : 40;
        slot->set_size(_width - 16, chart_h);
        auto chart = std::make_unique<HeroChart>();
        chart->set_size(_width - 16, chart_h);
        chart_ = chart.get();
        static_cast<zb::ui::Panel *>(slot)->add_child(std::move(chart));
    }

    // V-2: materialize the procedural assets once into the build's pixel
    // layout, then hand views to the gallery widgets -- the ball as an
    // alpha-blitted image, the shadow through the 9-slice card. Both
    // buffers are owned here so the views outlive every widget
    void Showcase::install_assets()
    {
        if (pages_[1] == nullptr)
        {
            return;
        }
        const auto &ball_src = showcase_assets::logo_ball_view;
        const auto &shadow_src = showcase_assets::card_shadow_view;
        const std::size_t ball_n =
            static_cast<std::size_t>(ball_src.width) * ball_src.height;
        const std::size_t shadow_n =
            static_cast<std::size_t>(shadow_src.width) * shadow_src.height;
        // one resize before any view is taken: growth would invalidate
        asset_pixels_.resize(ball_n + shadow_n);
        for (std::size_t i = 0; i < ball_n; ++i)
        {
            asset_pixels_[i] = rgba_color(ball_src.rgba + 4 * i);
        }
        for (std::size_t i = 0; i < shadow_n; ++i)
        {
            asset_pixels_[ball_n + i] = rgba_color(shadow_src.rgba + 4 * i);
        }
        ball_img_ = {asset_pixels_.data(),
                     static_cast<int>(ball_src.width),
                     static_cast<int>(ball_src.height),
                     static_cast<int>(ball_src.width)};
        shadow_img_ = {asset_pixels_.data() + ball_n,
                       static_cast<int>(shadow_src.width),
                       static_cast<int>(shadow_src.height),
                       static_cast<int>(shadow_src.width)};

        if (auto *logo_slot = pages_[1]->find_by_id("logo_slot"))
        {
            static_cast<zb::ui::Panel *>(logo_slot)
                ->add_child(std::make_unique<AlphaImage>(ball_img_));
        }
        if (auto *shadow_slot = pages_[1]->find_by_id("shadow_slot"))
        {
            auto card = std::make_unique<ShadowCard>(shadow_img_, ball_img_);
            card->set_size(shadow_slot->get_size());
            static_cast<zb::ui::Panel *>(shadow_slot)->add_child(std::move(card));
        }
    }

    void Showcase::wire_controls()
    {
        if (pages_[0] != nullptr)
        {
            auto *start_btn = static_cast<zb::ui::Button *>(pages_[0]->find_by_id("start_btn"));
            auto *stop_btn = static_cast<zb::ui::Button *>(pages_[0]->find_by_id("stop_btn"));
            auto *gallery_btn = static_cast<zb::ui::Button *>(pages_[0]->find_by_id("gallery_btn"));
            theme_btn_ = static_cast<zb::ui::Button *>(pages_[0]->find_by_id("theme_btn"));
            state_label_ = static_cast<zb::ui::Label *>(pages_[0]->find_by_id("state_value"));
            cpu_bar_ = static_cast<zb::ui::ProgressBar *>(pages_[0]->find_by_id("cpu_bar"));
            mem_bar_ = static_cast<zb::ui::ProgressBar *>(pages_[0]->find_by_id("mem_bar"));
            temp_bar_ = static_cast<zb::ui::ProgressBar *>(pages_[0]->find_by_id("temp_bar"));
            auto *replay_btn = static_cast<zb::ui::Button *>(pages_[0]->find_by_id("replay_btn"));
            if (start_btn != nullptr)
            {
                sub_start_ = start_btn->clicked.subscribe([this] { start(); });
            }
            if (stop_btn != nullptr)
            {
                sub_stop_ = stop_btn->clicked.subscribe([this] { stop(); });
            }
            if (replay_btn != nullptr)
            {
                sub_replay_ = replay_btn->clicked.subscribe([this] { replay(); });
            }
            if (gallery_btn != nullptr)
            {
                sub_gallery_ = gallery_btn->clicked.subscribe([this] { show_page(1); });
            }
            if (theme_btn_ != nullptr)
            {
                sub_theme_ = theme_btn_->clicked.subscribe([this] { toggle_theme(); });
                // the design file ships the light-theme caption; the
                // showcase boots dark, so the button offers light first
                theme_btn_->set_text(dark_ ? "LIGHT" : "DARK");
            }
        }
        if (pages_[1] != nullptr)
        {
            auto *back_btn = static_cast<zb::ui::Button *>(pages_[1]->find_by_id("back_btn"));
            demo_slider_ = static_cast<zb::ui::Slider *>(pages_[1]->find_by_id("demo_slider"));
            demo_bar_ = static_cast<zb::ui::ProgressBar *>(pages_[1]->find_by_id("demo_bar"));
            if (back_btn != nullptr)
            {
                sub_back_ = back_btn->clicked.subscribe([this] { show_page(0); });
            }
            if (demo_slider_ != nullptr && demo_bar_ != nullptr)
            {
                sub_slider_ = demo_slider_->changed.subscribe(
                    [this](const int v) { demo_bar_->set_value(v); });
            }
        }

        // button captions also center horizontally (every widget is
        // vertically centered at materialization)
        const auto center_button = [this](const char *id) {
            for (auto &page : pages_)
            {
                if (page != nullptr)
                {
                    if (auto *w = page->find_by_id(id))
                    {
                        w->set_h_align(zb::ui::Widget::h_align::center);
                    }
                }
            }
        };
        for (const char *id : {"start_btn", "stop_btn", "gallery_btn", "theme_btn",
                               "replay_btn", "back_btn", "demo_button"})
        {
            center_button(id);
        }
    }

    void Showcase::show_page(const int index)
    {
        if (index < 0 || index > 1 || pages_[index] == nullptr)
        {
            return;
        }
        zb::ui::Panel &root = window_->root();
        if (mounted_ != nullptr)
        {
            // park the outgoing page back into the array (the tree owns
            // it while mounted, so pages_[current_] was empty)
            if (auto parked = root.remove_child(mounted_))
            {
                pages_[current_].reset(
                    static_cast<zb::ui::FlexPanel *>(parked.release()));
            }
            mounted_ = nullptr;
        }
        zb::ui::FlexPanel *raw = pages_[index].get();
        root.add_child(std::move(pages_[index]));
        mounted_ = raw;
        current_ = index;
        root.layout();
    }

    void Showcase::set_state(const char *text)
    {
        if (state_label_ != nullptr)
        {
            state_label_->set_text(text);
        }
    }

    void Showcase::start()
    {
        if (cpu_bar_ != nullptr && cpu_bar_->get_value() >= cpu_bar_->get_max())
        {
            // DONE: restart from zero
            cpu_bar_->set_value(0);
            if (mem_bar_ != nullptr) mem_bar_->set_value(0);
            if (temp_bar_ != nullptr) temp_bar_->set_value(0);
        }
        running_ = true;
        set_state("RUNNING");
    }

    void Showcase::stop()
    {
        running_ = false;
        set_state("IDLE");
    }

    void Showcase::toggle_theme()
    {
        dark_ = !dark_;
        zb::ui::set_theme(dark_ ? zb::ui::dark_theme() : zb::ui::light_theme());
        if (theme_btn_ != nullptr)
        {
            theme_btn_->set_text(dark_ ? "LIGHT" : "DARK");
        }
    }

    // F-2 preview glue: restart the chart reveal. One Tween step per
    // paint() request (frame index = paint call), deterministic for the
    // recorder and the automation suites; hosts that pump frames see the
    // full animation, event-driven shells advance it on input
    void Showcase::replay()
    {
        reveal_.start(0, 255, 8);
        if (chart_ != nullptr)
        {
            chart_->set_progress(0);
        }
    }

    // one deterministic step per input event while running (repaint on
    // demand: there is no animation loop); the status label changes only
    // on the discrete DONE transition, never in this per-event path
    void Showcase::advance()
    {
        if (cpu_bar_ != nullptr) cpu_bar_->set_value(cpu_bar_->get_value() + 1);
        if (mem_bar_ != nullptr) mem_bar_->set_value(mem_bar_->get_value() + 2);
        if (temp_bar_ != nullptr) temp_bar_->set_value(temp_bar_->get_value() + 3);
        if (cpu_bar_ != nullptr && mem_bar_ != nullptr && temp_bar_ != nullptr &&
            cpu_bar_->get_value() >= cpu_bar_->get_max() &&
            mem_bar_->get_value() >= mem_bar_->get_max() &&
            temp_bar_->get_value() >= temp_bar_->get_max())
        {
            running_ = false;
            set_state("DONE");
        }
    }

    zb::SharedPtr<IWindow> Showcase::window() noexcept
    {
        return window_;
    }

    void Showcase::input(const zb::input::input_event &ev) noexcept
    {
        if (running_)
        {
            advance();
        }
        window_->input(ev);
    }

    void Showcase::paint() noexcept
    {
        // one deterministic tween step per paint request, BEFORE the
        // frame renders; marking the chart dirty keeps is_dirty() true
        // while a frame is owed, so idle-polling shells (NDS, linux-fb)
        // keep pumping and stop the moment the reveal lands
        if (reveal_.active())
        {
            reveal_.step();
            if (chart_ != nullptr)
            {
                chart_->set_progress(reveal_.value());
            }
        }
        window_->paint();
    }

    bool Showcase::is_dirty() const noexcept
    {
        return window_ && window_->is_dirty();
    }

    bool Showcase::dirty_region(int &x, int &y, int &rw, int &rh) const noexcept
    {
        return window_ && window_->dirty_region(x, y, rw, rh);
    }

    void Showcase::on_painting(const event::PAINT_EVENT::EventHandler handler) noexcept
    {
        if (window_) window_->painting += handler;
    }

    void Showcase::on_painted(const event::PAINT_EVENT::EventHandler handler) noexcept
    {
        if (window_) window_->painted += handler;
    }

    void Showcase::on_closing(const event::CLOSE_EVENT::EventHandler handler) noexcept
    {
        if (window_) window_->closing += handler;
    }

    void Showcase::on_closed(const event::CLOSE_EVENT::EventHandler handler) noexcept
    {
        if (window_) window_->closed += handler;
    }
}  // namespace zb::app::showcase
