/*
 * bytes_embed — generic file-to-C-array header embedder (the
 * html_embed/ui_embed precedent, for non-document binary assets:
 * today the showcase's packed Inter TTF blob).
 *
 * Usage: bytes_embed <out.gen.hpp> <symbol> <file> [file...]
 *
 * Each file lands as `static const unsigned char <symbol>[]` plus
 * `static const size_t <symbol>_len`, NUL-terminated beyond the data
 * (the html_embed convention). A missing file makes the tool exit 1 —
 * build-time materialization fails the build.
 */
#include <cstdio>
#include <string>
#include <vector>

int main(int argc, char *argv[])
{
    if (argc < 4)
    {
        std::fprintf(stderr, "usage: bytes_embed <out.gen.hpp> <symbol> <file> [file...]\n");
        return 1;
    }
    const char *out_path = argv[1];
    const char *symbol = argv[2];

    std::FILE *out = std::fopen(out_path, "wb");
    if (out == nullptr)
    {
        std::fprintf(stderr, "bytes_embed: cannot write %s\n", out_path);
        return 1;
    }
    std::fprintf(out, "// generated by bytes_embed -- do not edit\n");
    std::fprintf(out, "#pragma once\n#include <cstddef>\n\n");

    for (int i = 3; i < argc; ++i)
    {
        std::FILE *f = std::fopen(argv[i], "rb");
        if (f == nullptr)
        {
            std::fprintf(stderr, "bytes_embed: cannot read %s\n", argv[i]);
            std::fclose(out);
            return 1;
        }
        std::fprintf(out, "static const unsigned char %s[] =\n{\n", symbol);
        unsigned char buf[4096];
        size_t n = 0;
        size_t total = 0;
        int col = 0;
        while ((n = std::fread(buf, 1, sizeof(buf), f)) > 0)
        {
            for (size_t j = 0; j < n; ++j)
            {
                std::fprintf(out, "%s0x%02x,", col == 0 ? "  " : "", buf[j]);
                col = (col + 1) % 16;
                if (col == 0)
                {
                    std::fprintf(out, "\n");
                }
                ++total;
            }
        }
        const bool ok = std::ferror(f) == 0;
        std::fclose(f);
        if (!ok || total == 0)
        {
            std::fprintf(stderr, "bytes_embed: short read on %s\n", argv[i]);
            std::fclose(out);
            return 1;
        }
        if (col != 0)
        {
            std::fprintf(out, "\n");
        }
        // one 0x00 sentinel beyond the data (html_embed convention)
        std::fprintf(out, "  0x00};\n");
        std::fprintf(out, "static const size_t %s_len = %zu;\n\n", symbol, total);
    }
    std::fclose(out);
    return 0;
}
