/*
 * html_embed — build-time HTML design file packer.
 *
 * Usage: html_embed <out_header> <file.html>...
 *
 * The ui_embed precedent for .ui documents: reads each HTML document,
 * validates it with the *same* parser the app uses (parse_html), then
 * generates a C++ header embedding the raw document bytes:
 *
 *   static const embedded_html_file kHtmlFiles[] = { {"space.html", ...}, ... };
 *   static inline const embedded_html_file *find_html_file(const char *name);
 *
 * A document that does not parse (yields no widget) makes the tool exit
 * non-zero, so the CMake custom command fails the build: the
 * "build-time validation" guarantee, without a second parser. Embedded
 * bytes are the raw UTF-8 text plus one trailing 0x00 sentinel (the size
 * field excludes the sentinel): parse_html scans for a NUL terminator,
 * so the embedded array must carry the same shape pass 1 validated. At
 * runtime the app feeds them to parse_html + build() — the exact code
 * path desktop apps use with external files, so NDS (no filesystem) is
 * just another source.
 *
 * The generated header only needs the struct below; it does not include
 * any framework header (the consumer decides how to parse the bytes).
 */
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

#include "html.hpp"

namespace
{
    // "command center.html" -> command_center_html
    std::string symbol_of(const std::string &name)
    {
        std::string out;
        for (const char c : name)
        {
            const bool ident = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
                               || (c >= '0' && c <= '9') || c == '_';
            out.push_back(ident ? c : '_');
        }
        if (out.empty())
        {
            out = "html";
        }
        if (!(out[0] == '_' || std::isalpha(static_cast<unsigned char>(out[0]))))
        {
            out.insert(out.begin(), '_');
        }
        return out;
    }

    std::string file_base(const std::string &path)
    {
        const std::size_t slash = path.find_last_of("/\\");
        std::string base = slash == std::string::npos ? path : path.substr(slash + 1);
        const std::size_t dot = base.rfind('.');
        return dot == std::string::npos ? base : base.substr(0, dot);
    }

    // "dir/space.html" -> "space.html": the lookup name is the basename
    // (with extension), so find_html_file matches regardless of the
    // directory the build ran from
    std::string file_name(const std::string &path)
    {
        const std::size_t slash = path.find_last_of("/\\");
        return slash == std::string::npos ? path : path.substr(slash + 1);
    }

    bool read_file(const char *path, std::vector<unsigned char> &out)
    {
        FILE *f = std::fopen(path, "rb");
        if (f == nullptr)
        {
            return false;
        }
        std::fseek(f, 0, SEEK_END);
        const long size = std::ftell(f);
        std::fseek(f, 0, SEEK_SET);
        out.resize(size > 0 ? static_cast<std::size_t>(size) : 0);
        const bool ok =
            out.empty() || std::fread(out.data(), 1, out.size(), f) == out.size();
        std::fclose(f);
        return ok;
    }
}  // namespace

int main(int argc, char **argv)
{
    if (argc < 3)
    {
        std::fprintf(stderr, "usage: html_embed <out_header> <file.html>...\n");
        return 2;
    }

    const std::vector<std::string> inputs(argv + 2, argv + argc);

    // pass 1: validate every document with the library parser
    for (const std::string &path : inputs)
    {
        std::vector<unsigned char> bytes;
        bool ok_read = read_file(path.c_str(), bytes);
        bool ok_parse = false;
        if (ok_read)
        {
            bytes.push_back(0);  // NUL-terminate for the parser
            bool ok = false;
            zb::ui::parse_html(reinterpret_cast<const char *>(bytes.data()), &ok);
            ok_parse = ok;
        }
        if (!ok_read || !ok_parse)
        {
            std::fprintf(stderr, "html_embed: %s: %s\n", path.c_str(),
                         ok_read ? "document yields no widget" : "cannot read file");
            return 1;
        }
    }

    // pass 2: emit the header
    FILE *out = std::fopen(argv[1], "w");
    if (out == nullptr)
    {
        std::fprintf(stderr, "html_embed: cannot write %s\n", argv[1]);
        return 2;
    }

    std::fprintf(out, "#pragma once\n");
    std::fprintf(out, "// generated by html_embed — do not edit\n");
    std::fprintf(out, "// each data[] ends with one 0x00 sentinel beyond size;\n");
    std::fprintf(out, "// parse_html scans for the NUL terminator\n");
    std::fprintf(out, "#include <cstddef>\n");
    std::fprintf(out, "#include <cstring>\n");
    std::fprintf(out, "struct embedded_html_file\n{\n"
                      "    const char *name;\n"
                      "    const unsigned char *data;\n"
                      "    const std::size_t size;\n"
                      "};\n\n");

    struct doc
    {
        std::string path;
        std::string sym;
        std::string name;
        std::vector<unsigned char> bytes;
    };
    std::vector<doc> docs;
    for (const std::string &path : inputs)
    {
        doc d;
        d.path = path;
        d.name = file_name(path);
        d.sym = symbol_of(file_base(path)) + "_html";
        if (!read_file(path.c_str(), d.bytes))
        {
            std::fprintf(stderr, "html_embed: %s: cannot read file\n", path.c_str());
            std::fclose(out);
            return 1;
        }
        for (const auto &prev : docs)
        {
            if (prev.sym == d.sym || prev.name == d.name)
            {
                std::fprintf(stderr, "html_embed: %s and %s collide (%s)\n",
                             prev.path.c_str(), path.c_str(),
                             prev.sym == d.sym ? "same basename" : "same file name");
                std::fclose(out);
                return 1;
            }
        }
        // match the shape pass 1 validated: the parser needs the NUL
        // terminator, the size field below reports the document length
        d.bytes.push_back(0);
        docs.push_back(std::move(d));
    }

    for (const doc &d : docs)
    {
        std::fprintf(out, "static const unsigned char %s[] =\n{\n", d.sym.c_str());
        for (std::size_t i = 0; i < d.bytes.size(); ++i)
        {
            std::fprintf(out, "0x%02x,", d.bytes[i]);
            if (i % 16 == 15)
            {
                std::fprintf(out, "\n");
            }
        }
        std::fprintf(out, "\n};\n\n");
    }

    std::fprintf(out, "static const embedded_html_file kHtmlFiles[] =\n{\n");
    for (const doc &d : docs)
    {
        std::fprintf(out, "    {\"%s\", %s, sizeof(%s) - 1},\n", d.name.c_str(),
                     d.sym.c_str(), d.sym.c_str());
    }
    std::fprintf(out, "};\n\n");

    std::fprintf(out, "static inline const embedded_html_file *find_html_file(const char *name)\n"
                      "{\n"
                      "    for (const auto &f : kHtmlFiles)\n"
                      "    {\n"
                      "        if (f.name != nullptr && name != nullptr\n"
                      "            && std::strcmp(f.name, name) == 0)\n"
                      "        {\n"
                      "            return &f;\n"
                      "        }\n"
                      "    }\n"
                      "    return nullptr;\n"
                      "}\n");
    std::fclose(out);
    return 0;
}
